name: Tag creation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: '0'
          ssh-key: "${{ secrets.COMMIT_KEY }}"

    - name: Generate Git Tag
      id: generate_tag
      run: |
        set -x
        export BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        if [ "$BRANCH" = "main" ]; then
            RELEASE_PREFIX="production"
        elif [ "$BRANCH" = "release" ]; then
            RELEASE_PREFIX="staging"
        elif [ "$BRANCH" = "develop" ]; then
            RELEASE_PREFIX="development"
        else
            RELEASE_PREFIX="custom"
        fi

        VERSION_PREFIX="v"
        VERSION_MAJOR_MINOR="0.1"
        VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | cut -d '-' -f 1 | grep -oE '[0-9]+$') || unset VERSION_PATCH
        if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
        else
            VERSION_PATCH=$((VERSION_PATCH + 1))
        fi
        NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}-${RELEASE_PREFIX}"
        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Push Git Tag
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'olap74@users.noreply.github.com'
        git tag $NEW_TAG
        git push origin $NEW_TAG